### ISSUE TITLE
What changed?

### ISSUE THREAD

**Issue by MOZGIII** [emutex/ubilinux-kernel#1]
Could you please give a hint on what's changed in this kernel version since the upstream 4.9?
Is there a way to properly filter out git commits that are only in this fork?

**Comment by nicola-lunghi** [comment]
This repo is based on linux 4.9.45

**Comment by Thinstation** [comment]
You could try 
git format-patch 4b904b22bc906d5867933b8132ae4d7f31d7645d

**Comment by jbeta** [comment]
Or you can use this URL to view just the changes from the last stable tag:
https://github.com/emutex/ubilinux-kernel/compare/v4.9.45...upboard-4.9
