### ISSUE TITLE
Link is dead

### ISSUE THREAD

**Issue by machinekoder** [emutex/ubilinux-kernel#3]
The link in the description (https://up-community.org/wiki/Compile_ubilinux_kernel_from_source) is dead.
Where can I find instructions for compiling the kernel?

**Comment by machinekoder** [comment]
Found it https://wiki.up-community.org/Compile_ubilinux_kernel_from_source. Plese update the link

**Comment by filippobellini** [comment]
Thank you @machinekoder . The link has been updated.
Regards
